# Protocol Constants

# Client -> Server
MSG_ADD_POINT = "ADD_POINT"
MSG_CLEAR_POINTS = "CLEAR_POINTS"
MSG_START_TRAINING = "START_TRAINING"
MSG_STOP_TRAINING = "STOP_TRAINING"
MSG_RESET_MODEL = "RESET_MODEL"

# Server -> Client
MSG_TRAINING_STATUS = "TRAINING_STATUS"
MSG_MAP_UPDATE = "MAP_UPDATE"

# Defaults
DEFAULT_LEARNING_RATE = 0.01
